#-----------------------------------------------
#               Sky Changer Config
#-----------------------------------------------

# DO NOT CHANGE THIS VALUE.
# CHANGING IT COULD RESULT IN DATA LOSS.
ConfigVersion: 1.0

#--------------[General Settings]---------------
general_settings:

  # Upper packet limit. Scientific notation is accepted.
  # Must be less than 3.4028236E38 or there will be no limit.
  upper_limit: 50.0
  
  # Lower packet limit. Scientific notation is accepted.
  # Must be greater than -3.4028236E38 or there will be no limit.
  lower_limit: -50.0
  
  # Choose the language of this plugin. The value must be supported
  # and follow the format "language_COUNTRY". For example en_US.
  # Submit Translations: https://bitbucket.org/AventiumSoftworks/skychanger/issues
  # Supported languages:
  # - en_US (English, United States)
  # - it_IT (Italiano, Italia)
  # - de_DE (Deutsche, Deutschland)
  # - nl_NL (Nederlands, Nederland)
  # - es_EC (Español, Ecuador)
  # - es_AR (Español, Argentina)
  # - no_NO (Norsk, Norge)
  language: en_US