#
# This file is part of SkyChanger, licensed under the MIT License (MIT).
#
# Copyright (c) 2017-2018 Daniel D. Scalzi <https://github.com/dscalzi/SkyChanger>
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#

#-----------------------------------------------
#               Sky Changer Config
#-----------------------------------------------
# DO NOT CHANGE THIS VALUE.
# CHANGING IT COULD RESULT IN DATA LOSS.
ConfigVersion: 1.0

#--------------[General Settings]---------------
general_settings:

  # Upper packet limit. Scientific notation is accepted.
  # Must be less than 3.4028236E38 or there will be no limit.
  upper_limit: 50.0
  
  # Lower packet limit. Scientific notation is accepted.
  # Must be greater than -3.4028236E38 or there will be no limit.
  lower_limit: -50.0
  
  # Choose the language of this plugin. The value must be supported
  # and follow the format "language_COUNTRY". For example en_US.
  # Submit Translations: https://github.com/dscalzi/SkyChanger/wiki/Translation-Guide
  # Supported languages:
  # - en_US (English, United States)
  # - it_IT (Italiano, Italia)
  # - de_DE (Deutsche, Deutschland)
  # - nl_NL (Nederlands, Nederland)
  # - es_EC (Español, Ecuador)
  # - es_AR (Español, Argentina)
  # - no_NO (Norsk, Norge)
  # - iw_IL (ישראל, עברית)
  # - hu_HU (Magyar, Magyarország)
  # - zh_CN (简体中文, 中国)
  language: en_US