#-----------------------------------------------
#               Sky Changer Config
#-----------------------------------------------

# DO NOT CHANGE THIS VALUE.
# CHANGING IT COULD RESULT IN DATA LOSS.
ConfigVersion: 1.0

#--------------[General Settings]---------------
general_settings:

  # Upper packet limit. Scientific notation is accepted.
  # Must be less than 3.4028236E38 or there will be no limit.
  upper_limit: 50.0
  
  # Lower packet limit. Scientific notation is accepted.
  # Must be greater than -3.4028236E38 or there will be no limit.
  lower_limit: -50.0