author: Daniel Scalzi
description: Spigot plugin to change the color of the sky in your Minecraft world.
main: com.dscalzi.skychanger.SkyChanger
name: SkyChanger
version: 1.0
commands:
  skychanger:
    description: Main plugin command
permissions:
  skychanger.*:
    children:
      skychanger.changesky.*:
        children:
          skychanger.changesky.self: true
          skychanger.changesky.others: true
          skychanger.changesky.all: true
      skychanger.bypasslimit: true
      skychanger.reload: true